### PR TITLE
fix: updated named to default export in types

### PR DESCRIPTION
**Pull request by RemeJuan**
Updated the types exports from named to default as the where being reexported as default exports in the index facade and this was throwing issue in webpack 4

https://github.com/Sharlaan/material-ui-superselectfield/issues/145

### CODE REVIEW

**Comment by Sharlaan** [comment]
Hi, thanks for the fix but where are the changes within all those 519 files ?

**Comment by RemeJuan** [comment]
@Sharlaan 

`es/types/selectFieldTypes.js`
`es/types/selectionsPresenterTypes.js`

Odd, changed 2 files myself, but seem the processes added a few hundred more...

**Comment by Sharlaan** [comment]
mmmm you should NOT touch anything in demo/dist/ es/ lib/ or umd/

these folders are managed by NWB

**Comment by RemeJuan** [comment]
@Sharlaan 

That is the precommit hook specified in the package.json file

`"precommit": "yarn fix && yarn clean && yarn build && git add es lib demo/dist && lint-staged"`

**Comment by Sharlaan** [comment]
Can you write an issue with a description of your error please ?

Yes it is this line which points to :  
`"build": "nwb build-react-component"`

**Comment by Sharlaan** [comment]
I just saw the author of NWB is currently upgrading to Webpack4, so hopefully he will fix the building process.

Have you tried with es5 version in lib/ ?

**Comment by RemeJuan** [comment]
I know that, but if demo should not be touched, then the build process should not be run for each and every single commit. That should be setup in the postmerge hook or maybe another independent process through a CI.

**Comment by Sharlaan** [comment]
Indeed, im doing that in Travis.yml

Thing is i wanted to run tests in precommit and prepush hooks, and thought needed to build for that....

**Comment by Sharlaan** [comment]
I think your changes got overriden by build process in Travis (triggered for any PR)

So can you write them in your issue ticket please ?

**Comment by RemeJuan** [comment]
@Sharlaan 

Fortunately not, test runners use the source code not the production code for testing, so you could remove the whole precommit hook, and have those run as part of the Travis process instead.

Let me dump this branch and open in a new PR, I know how to get just those 2 files only.

It is not Travis, I see on my branch the code was overwritten in the precommit line, I would guess eslint would have done that, mmm.

**Comment by Sharlaan** [comment]
My bad :
- precommit just eslint --fix + formats with Prettier
- prepush then don't have to fix/format and can run tests directly
- Travis finally takes over the building process in pre-Merge step

So yea since eslint applies only to src and demo/src, i should not need to build in precommit ...

I'm open to suggestions regarding workflow automation.

**Comment by RemeJuan** [comment]
So I see, I updated the wrong files though, the es folder I see is generated by the build command, so this PR is pretty useless, however for anyone else to be able to easily contribute, you should remove that precommit hook, or update it to just run linting and maybe prettier.

I never used prettier, I prefer my own opinion on code formatting, so our process triggers nothing on precommit, but I do run linting and tests on prepush, as we commit more verbosely, running those on each commit, when you changes like 10 pr so files and are committing only 1 or 2 at a time just got in the way of getting things done.

Depends on how you with to run the control, but anyone with a proper editor should have eslint running real time informing them of errors as they type, which we do so linting on prepush is pretty safe for us.

I am going to close this, update the correct 2 files and no-verify push to bypass that precommit so that you have just the files that have changed.

**Pull request closed without merging**
