### PR TITLE
feat: add popoverClassName

### PR DESCRIPTION
**Pull request by barrymichaeldoyle**
- Increment version number @1.8.7

### CODE REVIEW

**Comment by Sharlaan** [comment]
I went to your forked repo, it seems you made a merge after pushing your local `popoverClassName` branch ?
It is not needed for a PR here.

Try a `git reset --hard HEAD~1` to remove the merge commit, then `git push --force`: this should update the remote `popoverClassName` branch and then Github should update this PR automatically.

**Comment by Sharlaan** [comment]
Oooops i forgot something important:  

Can you add in your commit:
- Increment version number @1.8.7

This will trigger the release CI process after i merge your PR

**Comment by barrymichaeldoyle** [comment]
Ah right, thanks. Sorry, not really used to contributing, getting better :) I'll comment once I've done those steps.

**Comment by barrymichaeldoyle** [comment]
Ok...  I have no idea how to add "Increment version number @1.8.7" to my commit. And also, the reason that merge commit keeps popping up is because I always click Resolve Conflicts in the checks. So I'm not going to click it now and leave it there and wait for your advice on what to do.

Thanks for your patience.

**Comment by Sharlaan** [comment]
i committed your changes directly on my dev branch, closing your issue#139

**Comment by barrymichaeldoyle** [comment]
Ok cool thanks

**Pull request closed without merging**
