### PR TITLE
Allow empty Menu with AutoComplete if Threshold is 0

### PR DESCRIPTION
**Pull request by jwmann**
This is kind of needs #103 and #104 in order to fully work properly.

This feature allows the possibility for you to generate the items in the menu based on the input Text with an API call pulling the data.

Even without considering the feature, if you set the `showAutocompleteThreshold` to 0, ideally it should be able to show in the menu when there are 0 items. This allows that.

### CODE REVIEW

**Comment by Sharlaan** [comment]
What's the whole point to show the aurocomplete if there are no items to filter ?
Similarly, why show the autocomplete if there are less than X items (defaulted to 10) ?

**Comment by jwmann** [comment]
The point is similar to the asynchronous loading example.
The only difference is that call to load the data is based on what's in the input.

For example:
input: '123 Fake'

Will make an API call to search for strings and return a list with:
123 Fake Street
123 Fake Avenue
123 Fake Drive
123 Fake Boulevard

This would be impossible if A) the menu doesn't open at all, B) the autocomplete doesn't show. Which is how it works now.

All my recent PR's, including this one, don't change any of the default original functional in any way.
It's only different if you set your prop to `showAutocompleteThreshold={0}` and even then, it only does something different if there's no items.

**Comment by Sharlaan** [comment]
Can you change `showAutocompleteThreshold === 0` to this more expressive way  
`showAutocompleteThreshold === 'always'` please ?
Adjust propType accordingly as well.
Also don't forget to update the documentation for this property in the Readme.

**Comment by jwmann** [comment]
Absolutely, I'll have it done in the next 15-20 minutes

**Comment by jwmann** [comment]
It's actually a good thing we switched it to `always`.
I found a bug in my original PR where the `showAutocomplete` state would be overwritten by the `componentWillReceiveProps()` function and wouldn't show anymore.

Also, this allows for a possibility of having a `never` option as well in the future.

Let me know if you find anything else 👍

**Comment by Sharlaan** [comment]
Good job and nice catch indeed.

Would it be possible to be more strict on proptypes, ie explicitly assert for `'always'` instead of generic `string` ?

Good idea for 'never', some poeple seem to not grasp the concept of treshold higher than children.length...
Feel free to implement it on this same PR if you want. In that cas i'll wait for your updates before merging.

By the way, very nice catch on the undocumented `autoFocus` prop on your other PR, big thanks.

Same on tests, if you can help improve the coverage, it would be awesome and would help me learn as well !

**Comment by jwmann** [comment]
I'm not very familiar with writing tests in enzyme but I'm trying my best.
I need these changes for a project I'm working on so I'm hoping these can be published to `npm` as soon as possible. 

I've added the new changes you mentioned thus far though.

**Pull request merged**
