### PR TITLE
Implemented popoverClassName (with default props and types)

### PR DESCRIPTION
**Pull request by barrymichaeldoyle**

### CODE REVIEW

**Comment by Sharlaan** [comment]
Almost perfect PR, thanks

Can you add a description in Readme, after `noMatchFoundStyle` please ?
Can you also squash your commits into one with the PR's title, for cleaner history ?

**Comment by barrymichaeldoyle** [comment]
All done :+1:

**Comment by Sharlaan** [comment]
Sorry maybe my modified comment crossed your committing, but can you amend your last commit message with `feat: add popoverClassName` please ?

**Comment by barrymichaeldoyle** [comment]
Ok cool I think I've done it :1st_place_medal:

**Comment by Sharlaan** [comment]
That second commit is weird o.O ?  
`Merge branch 'master' into master`

**Comment by barrymichaeldoyle** [comment]
Yeah, it keeps giving me merge conflicts and then automatically does that to fix it. This is acting strangely...

**Comment by barrymichaeldoyle** [comment]
Making a new PR since this one just isn't working...

**Pull request closed without merging**
